[package]
name = "ctrlassist"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
ctrlc = "3.5.1"
env_logger = "0.11.8"
evdev = "0.13.2"
gilrs = "0.11.0"
log = "0.4.28"
udev = "0.9.3"
